@host = http://localhost:3000
@createdInvestmentId = {{createdInvestment.response.body.$.id}}
@token = {{signin.response.body.$.token}}

### Create User

# @name createdUser
POST {{host}}/users
Content-Type: application/json

{
  "name": "Luiz",
  "email": "luiz@email.com",
  "password": "12345678"
}

### Signin 401

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "luiz@email.com",
  "password": "321"
}

### Signin Ok

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "luiz@email.com",
  "password": "12345678"
}

### Read User (whitout token)

GET {{host}}/users/me

### Read User (with token)

GET {{host}}/users/me
Authorization: bearer {{token}}

### Read Categories

GET {{host}}/categories
Authorization: bearer {{token}}

### Read Category Pós

# @name categoryPos
GET {{host}}/categories?name=Pós
Authorization: bearer {{token}}

### Read Category IPCA

# @name categoryIpca
GET {{host}}/categories?name=IPCA
Authorization: bearer {{token}}

### Create Investment

@categoryIpcaId = {{categoryIpca.response.body.$.id}}

# @name createdInvestment
POST {{host}}/investments
Authorization: bearer {{token}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 10000,
  "interest": "100% Selic",
  "createdAt": "2023-09-01",
  "broker": "Banco Inter",
  "categoryId": "{{categoryIpcaId}}"
}

### Read Investments

GET {{host}}/investments
Authorization: bearer {{token}}

### Read Investments by Name

GET {{host}}/investments?name=Tesouro
Authorization: bearer {{token}}

### Read Investments by Id

GET {{host}}/investments/{{createdInvestmentId}}
Authorization: bearer {{token}}

### Update Investment

@categoryPosId = {{categoryPos.response.body.$.id}}

PUT {{host}}/investments/{{createdInvestmentId}}
Authorization: bearer {{token}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 20000,
  "interest": "100% Selic",
  "createdAt": "2023-09-01",
  "broker": "Banco Inter",
  "categoryId": "{{categoryPosId}}"
}

### Delete Investment

DELETE {{host}}/investments/{{createdInvestmentId}}
Authorization: bearer {{token}}

