@startuml
title Create
hide footbox
skinparam monochrome true

Client -> Server: POST /investments
note right: POST /investments HTTP/1.1\nHost: 127.0.0.1:3000\nContent-Type: application/json\n\n{\n  "name": "Tesouro IPCA 2029",\n  "value": 100\n}
Server -> Client: HTTP/1.1 201 Created
note left: HTTP/1.1 201 Created\n\n{\n  "id": 4197d9c8,\n  "name": "Tesouro IPCA 2029",\n  "value": 100\n}
@enduml
