@startuml
title Read
hide footbox
skinparam monochrome true

Client -> Server: GET /investments
note right: GET /investments HTTP/1.1\nHost: 127.0.0.1:3000
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\n\n[\n  {\n    "id": 4197d9c8,\n    "name": "Tesouro IPCA 2029",\n    "value": 100\n  }\n]
@enduml
