@startuml
title Update
hide footbox
skinparam monochrome true

Client -> Server: PUT /foods/4197d9c8
note right: PUT /foods/4197d9c8 HTTP/1.1\nHost: 127.0.0.1:3000\nContent-Type: application/json\n\n{\n  "name": "Tesouro IPCA 2029",\n  "value": 200\n}
Server -> Client: HTTP/1.1 200 Ok
note left: HTTP/1.1 200 Ok\n\n{\n  "id": 4197d9c8,\n  "name": "Tesouro IPCA 2029",\n  "value": 200\n}
@enduml
