@startuml
hide footbox
skinparam monochrome true
skinparam defaultTextAlignment center

circle 1 as " "

circle 2 as " "

file signinGet [
  /signin (Form)
]


node signinPost [
  /signin (Auth)
]

node signOut [
  /signout
]

node isAuthenticated [
  isAuthenticated
  (req.session.userId)
]

file home #gray [
  /home
]


isAuthenticated -down-> signinGet: GET
home <-up-> isAuthenticated
signOut -left-> signinGet: GET
1 -right-> signinGet: GET
signinPost -left-> signinGet: GET
signinPost -up[hidden]- isAuthenticated
signinPost -down[hidden]- signOut
signinGet -right-> signinPost: POST
home -down-> signOut: GET
signinPost -right-> home: GET
2 -left-> home: GET

@enduml
