@startuml
hide footbox
skinparam monochrome true

Client -> Server: GET /counter
note right: GET /counter HTTP/1.1\nHost: localhost:3000
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\nSet-Cookie: counter=1; Max-Age=360; Path=/; Expires=...\n\ncounter = 1
Client -> Server: GET /counter
note right: GET /counter HTTP/1.1\nHost: localhost:3000\nCookie: counter=1
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\nSet-Cookie: counter=2; Path=/\n\ncounter = 2
Client -> Server: GET /counter/clear
note right: GET /counter/clear HTTP/1.1\nHost: localhost:3000\nCookie: counter=2
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\nSet-Cookie: counter=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT\n\ncounter cleared

@enduml


