@startuml
skinparam monochrome true
title Cookie (HTTP)

node client [
  HTTP Client
]
node server [
  HTTP Server
]
database cookies

server -> client
client -right-> server
client -left-> cookies
cookies -right-> client
@enduml

Response
Resquest
