@startuml
hide footbox
skinparam monochrome true

Client -> Server: GET /counter
note right: GET /counter HTTP/1.1\nHost: localhost:3000
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\nSet-Cookie: connect.sid=s%3AL483...; Path=/; HttpOnly\n\ncounter = 1
Client -> Server: GET /counter
note right: GET /counter HTTP/1.1\nHost: localhost:3000\nCookie: connect.sid=s%3AL483...
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\n\ncounter = 2
Client -> Server: GET /counter
note right: GET /counter HTTP/1.1\nHost: localhost:3000\nCookie: connect.sid=s%3AL483...
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\n\ncounter = 3
Client -> Server: GET /counter/clear
note right: GET /counter/clear HTTP/1.1\nHost: localhost:3000\nCookie: connect.sid=s%3AL483...
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\n\ncounter cleared
Client -> Server: GET /counter
note right: GET /counter HTTP/1.1\nHost: localhost:3000\nCookie: connect.sid=s%3AL483...
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\n\ncounter = 1

@enduml


