@startuml
skinparam monochrome true
title Session (HTTP)

node client as "HTTP Client"
node server as "HTTP Server"
database cookies
database session
database sid1 as "sid 1"
label sid as "..."
database sidN as "sid N"

server -left-> client
client -right-> server
client -left-> cookies
cookies -right-> client
session -left-> server
server -right-> session
session -down- sid1
session -down- sid
session -down- sidN
@enduml

Response
Resquest
