### Cadastrar
POST http://localhost:3000/signup
Content-Type: application/x-www-form-urlencoded

name=Luiz
&email=luiz@email.com
&password=123
&confirm_password=123

### Login

# @name login
POST http://localhost:3000/signin
Content-Type: application/x-www-form-urlencoded

email=luiz@email.com
&password=123

### Create Food
# @connect.sid = {{login.response.headers.setcookie}}
@connect.sid = s%3AuMCNUKfqEj2--w4AOc25CHlrVnrve8mv.07PuhDlYd7nOpi74G0i1QImLqP5OtM5pqGPfG2bFoi4

POST http://localhost:3000/foods
Content-Type: multipart/form-data; boundary=------WebKitFormBoundary0Rn0iIFwMLe339S6
Content-Disposition: form-data; name=\"name\"
Cookie: connect.sid={{connect.sid}}


Batata Frita
------WebKitFormBoundary0Rn0iIFwMLe339S6
Content-Disposition: form-data; name=\"price\"

9
------WebKitFormBoundary0Rn0iIFwMLe339S6
Content-Disposition: form-data; name=\"category_id\"

1
------WebKitFormBoundary0Rn0iIFwMLe339S6
Content-Disposition: form-data; name=\"image_path\"


------WebKitFormBoundary0Rn0iIFwMLe339S6
Content-Disposition: form-data; name=\"image\"; filename=\"batatafrita.jpg\"
Content-Type: image/jpeg

< ./public/imgs/batatafrita.jpg
------WebKitFormBoundary0Rn0iIFwMLe339S6--

### Read Foods

GET http://localhost:3000/foods/index

### Update Food

PUT http://localhost:3000/foods/5
Content-Type: application/json

{
  "name": "Batata Frita",
  "image": "/imgs/batatafrita.jpg",
  "price": 5.5,
  "category_id": 1
}

### Delete Food

DELETE http://localhost:3000/foods/5
