@startuml
hide circle
skinparam linetype ortho
skinparam monochrome true
left to right direction

entity "Food" as food {
  *id : integer
  name : text
  image : text
  price: double
  *category_id : integer <<FK>>
}

entity "Category" as category {
  *id : integer
  name : text
}

food ||--|{ category
@enduml
