### Create Host

POST http://localhost:3000/hosts
Content-Type: application/json

{
  "name": "PC 2",
  "address": "192.168.0.2",
  "mask": "255.255.255.0"
}


### Read Hosts

GET http://localhost:3000/hosts

### Read Host by ID

GET http://localhost:3000/hosts/3

### Update Host

PUT http://localhost:3000/hosts/3
Content-Type: application/json

{
  "name": "PC 2",
  "address": "192.168.0.20",
  "mask": "255.255.255.0"
}

### Delete Host

DELETE http://localhost:3000/hosts/3
