@host = http://localhost:3000/api
@createdInvestmentId = {{createdInvestment.response.body.$.id}}

### Create Investment

# @name createdInvestment
POST {{host}}/investments
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 20000
}

### Create Investment without value

POST {{host}}/investments
Content-Type: application/json

{
  "name": "Tesouro Selic 2029"
}

### Create Investment without investment values

POST {{host}}/investments

### Read Investments

GET {{host}}/investments

### Read Investments by id

GET {{host}}/investments/{{createdInvestmentId}}

### Read Investments by invalid id

GET {{host}}/investments/a

### Read Investments by Name

GET {{host}}/investments?name=Selic

### Update Investment

PUT {{host}}/investments/{{createdInvestmentId}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 25000
}

### Update Investment without value

PUT {{host}}/investments/{{createdInvestmentId}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029"
}

### Update Investment with invalid id

PUT {{host}}/investments/a
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 25000
}

### Delete Investment

DELETE {{host}}/investments/{{createdInvestmentId}}

### Delete Investment with invalid id

DELETE {{host}}/investments/a
