@startuml
title Read
hide footbox
skinparam monochrome true
skinparam backgroundcolor darkgray

Client -> Server: GET /hosts
note right: GET /hosts HTTP/1.1\nHost: 127.0.0.1:3000
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\n\n[\n  {\n    "name": "Server",\n    "address": "10.0.0.10",\n    "mask": "255.255.255.0",\n    "id": 1\n  },\n  {\n    "name": "PC 1",\n    "address": "192.168.0.1",\n    "mask": "255.255.255.0",\n    "id": 2\n  },\n  {\n    "name": "PC 2",\n    "address": "192.168.0.2",\n    "mask": "255.255.255.0",\n    "id": 3\n  }\n]
@enduml
