@startuml
title Update
hide footbox
skinparam monochrome true
skinparam backgroundcolor darkgray

Client -> Server: PUT /hosts/3
note right: PUT /hosts/3 HTTP/1.1\nHost: 127.0.0.1:3000\nContent-Type: application/json\n\n{\n  "name": "PC 2",\n  "address": "192.168.0.20",\n  "mask": "255.255.255.0",\n}
Server -> Client: HTTP/1.1 200 Ok
note left: HTTP/1.1 200 Ok\n\n{\n  "name": "PC 2",\n  "address": "192.168.0.20",\n  "mask": "255.255.255.0",\n  "id": 3\n}
@enduml
