@startuml
hide footbox
skinparam monochrome true

rectangle layout [
  <b>Layout
  <html>
  ...
  <body>
  {% block content %}
  {% endblock %}
  </body>
  <html>
]

rectangle njk [
  <b>Page (NJK)
  {% block content %}
  <ul>
  {% for food of foods %}
    <li>{{ food }}</li>
  {% endfor %}
  <ul>
  {% endblock %}
]

rectangle data [
  <b>Data (foods)
  "Salada",
  "Hambúrguer",
  "Sanduíche"
]

rectangle engine [
  <b>Template Engine (NJK)
]

rectangle html [
  <b>Page (HTML)
  <html>
  ...
  <body>
  <ul>
    <li>Salada</li>
    <li>Hambúrguer</li>
    <li>Sanduíche</li>
  <ul>
  </body>
  <html>
]

layout .right.> njk
njk -right-> engine
data -down-> engine
engine -> html
@enduml
