@startuml
title Nunjucks
hide footbox
skinparam monochrome true
skinparam defaultTextAlignment center

rectangle layout [
  Layout
]

rectangle njk [
  Page (NJK)
]

rectangle engine [
  Template Engine
]

rectangle html [
  Page (HTML)
]

rectangle data [
  Data
]

layout .right.> njk
njk -right-> engine
data -down-> engine
engine -> html
@enduml
