@startuml
title Hello HTTP
hide footbox
skinparam monochrome true

Client -> Server: HTTP Request (req)
note right: GET / HTTP/1.1\nHost: 127.0.0.1:3000
Server -> Client: HTTP Response (res)
note left: HTTP/1.1 200 OK\n\nHello World!
@enduml
