@startuml
title Update
hide footbox
skinparam monochrome true

Client -> Server: PUT /foods/1
note right: PUT /foods/1 HTTP/1.1\nHost: 127.0.0.1:3000\nContent-Type: application/json\n\n{\n  "name": "Salada 1",\n  "price": 16.5\n}
Server -> Client: HTTP/1.1 200 Ok
note left: HTTP/1.1 200 Ok\n\n{\n  "id": 1,\n  "name": "Salada 1",\n  "price": 16.5\n}
Client -> Server: PUT /foods/a
note right: PUT /foods/a HTTP/1.1\nHost: 127.0.0.1:3000\nContent-Type: application/json\n\n{\n  "name": "Salada 1",\n  "price": 16.5\n}
Server -> Client: HTTP/1.1 400 Bad Request
note left: HTTP/1.1 400 Bad Request\n\n{\n  "error": "Food not found."\n}
@enduml
