@host = http://localhost:3000
@createdInvestmentId = {{createdInvestment.response.body.$.id}}
@createdUserId = {{createdUser.response.body.$.id}}

### Create User

# @name createdUser
POST {{host}}/users
Content-Type: application/json

{
  "name": "Luiz",
  "email": "luiz@email.com",
  "password": "123"
}

### Read Categories

GET {{host}}/categories

### Read Categories by Name

# @name categoryPos
GET {{host}}/categories?name=Pós

### Read Categories by Name

# @name categoryIpca
GET {{host}}/categories?name=IPCA

### Create Investment

@categoryIpcaId = {{categoryIpca.response.body.$.id}}

# @name createdInvestment
POST {{host}}/investments
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 10000,
  "categoryId": "{{categoryIpcaId}}",
  "userId": "{{createdUserId}}"
}

### Read Investments

GET {{host}}/investments

### Read Investments by Name

GET {{host}}/investments?name=Tesouro

### Update Investment

@categoryPosId = {{categoryPos.response.body.$.id}}

PUT {{host}}/investments/{{createdInvestmentId}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2029",
  "value": 20000,
  "categoryId": "{{categoryPosId}}",
  "userId": "{{createdUserId}}"
}

### Delete Investment

DELETE {{host}}/investments/{{createdInvestmentId}}

