@startuml
title MVC
hide footbox
skinparam monochrome true
skinparam defaultTextAlignment center

rectangle Browser [
  <b>Browser
]
rectangle Loader [
  <b>Loader
  index.js
]
rectangle Router [
  <b>Router
  routes/index.js
]
rectangle Controller [
  <b>Controller
  controllers/foodsController.js
]
rectangle Model [
  <b>Model
  models/Food.js
  models/Category.js
]
rectangle Seed [
  <b>Seed
  seeders/index.js
  seeders/data.json
]
rectangle Migration [
  <b>Migrations
  migrations/index.js
]
rectangle View [
  <b>View
  views/layout.njk
  views/foods/index.njk
  views/foods/_delete.njk
]
database Database [
  <b>Database
  db/database.sqlite
]

Browser -right-> Router: 1. /foods/index
Router -right-> Controller: 2. index
Model -up-> Controller: 5. JSON
Controller -down-> Model: 3. readAll
Model <-down-> Database: 4. SQL
View -down-> Controller: 7. HTML
Controller -up-> View: 6. foods
Controller -left-> Browser : 8. HTML
Loader .up.> Router
Loader .down.> Seed: up
Seed .right.> Model: create
Migration ..> Database: SQL
Loader .down.> Migration: up
View -[hidden]- Controller
Migration -right[hidden]- Seed
Controller -left[hidden]- Browser
Seed -right[hidden]- Model
Seed -down[hidden]- Database

@enduml
