@startuml
title MVC
hide footbox
skinparam monochrome true
skinparam defaultTextAlignment center

rectangle Browser [
  <b>Browser
]
rectangle View [
  <b>View
  public/foods.njk
]
rectangle Router [
  <b>Router
  routes/index.js
]
rectangle Controller [
  <b>Controller
  controllers/foodsController.js
]
rectangle Loader [
  <b>Loader
  index.js
]
rectangle Seed [
  <b>Seed
  seeders/index.js
]
rectangle Model [
  <b>Model
  models/Food.js
]
database Database [
  <b>Database
  Array & Key
]

View -up-> Browser: 1. foods
Browser -up-> View: 8. JSON
Browser -right-> Router: 2. /foods/index
Controller -left-> Browser : 7. JSON
Router -right-> Controller: 3. index
Controller <-down-> Model: 4. Food.readAll
Controller <-down-> Model: 6. JSON
Model <-down-> Database: 5. JSON
Loader .up.> Router
Loader .down.> Seed: Seed.up
Seed .right.> Model: Food.create
Router -right[hidden]- Controller

@enduml
