### Signup
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "Luiz Carlos",
  "email": "luiz.carlos@email.com",
  "password": "123",
  "confirm_password": "123"
}

### Signin
# @name signin
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "luiz.carlos@email.com",
  "password": "123"
}

### Create Food
# @name createFood
POST http://localhost:3000/foods
Content-Type: application/json
Authorization: Bearer {{signin.response.body.$.token}}

{
  "name": "Batata Frita",
  "image": "/imgs/batatafrita.jpg",
  "price": 5,
  "category_id": 1
}

### Read Foods
GET http://localhost:3000/foods
Authorization: Bearer {{signin.response.body.$.token}}

### Update Food
PUT http://localhost:3000/foods/{{createFood.response.body.$.id}}
Authorization: Bearer {{signin.response.body.$.token}}
Content-Type: application/json

{
  "name": "Batata Frita",
  "image": "/imgs/batatafrita.jpg",
  "price": 5.5,
  "category_id": 1
}

### Delete Food
DELETE http://localhost:3000/foods/{{createFood.response.body.$.id}}
Authorization: Bearer {{signin.response.body.$.token}}
